project_id = "oeghvplwcsxhimxvozzb"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
major_version = 17

[auth]
enabled = true
site_url = "io.supabase.telomy://login-callback"
additional_redirect_urls = ["io.supabase.telomy://login-callback"]
jwt_expiry = 3600
enable_signup = true
